### PR TITLE
Allow react ^16.0.0

### PR DESCRIPTION
**Pull request by andreyvital**

### CODE REVIEW

**Comment by jvt** [comment]
Any chance of getting this merged in @gaearon?

**Comment by pdeva** [comment]
pinging @gaearon again to merge this..

**Comment by gaearon** [comment]
I'm not actively maintaining this project (sorry, I have too many).
For the last few years @zalmoxisus has been helping out, but maybe he's too busy.

If you're interested in taking over, please DM me on Twitter and I'll give you the perms.

**Comment by jvt** [comment]
Hey everyone, I'll now be helping out with maintaining this project!

**Comment by jvt** [comment]
I'll review this tonight when I get to my computer.

**Comment by jvt** [comment]
Thanks for your contribution! It's published as `redux-devtools-dock-monitor@1.1.3`.

**Pull request merged**
